####  CONFIGURATION SPECIFIC ####
hostname: MOW-CSR-01


standard_acls:
  ACL_FOR_NAT:
    - permit 172.30.0.0 0.0.255.255


default_route: 132.87.2.254

l3_interfaces:
  - interface_type: GigabitEthernet
    interface_id: 1
    description: SW3_uplink
    shutdown: false
  - interface_type: GigabitEthernet
    interface_id: 0/2
    description: INET11
    ipv4_address: 20.17.5.2/30
    shutdown: false
  - interface_type: Loopback
    interface_id: 101
    description: 
    ipv4_address: 11.11.11.11/32
    ipv6_address: dead:beef:11::1/128
    shutdown: false
  - interface_type: Tunnel
    interface_id: 100
    description: DMVPN
    ipv6_address: 2001::11/64
    source: Loopback101
    mode: gre multipoint
    shutdown: false