name: test-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VIRL2_URL: ${{ secrets.VIRL2_URL }}
  VIRL2_USER: ${{ secrets.VIRL2_USER }}
  VIRL2_PASS: ${{ secrets.VIRL2_PASS }}

jobs:
  test:
    runs-on: cml2-controller

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo $VIRL2_URL >> test_url

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
