name: test-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VIRL2_URL: ${{ secrets.VIRL2_URL }}
  VIRL2_USER: ${{ secrets.VIRL2_USER }}
  VIRL2_PASS: ${{ secrets.VIRL2_PASS }}
  VIRL2_NODES_USER: ${{ secrets.VIRL2_NODES_USER }}
  VIRL2_NODES_PASS: ${{ secrets.VIRL2_NODES_PASS }}
  VIRL2_NODES_BECOME: ${{ secrets.VIRL2_NODES_BECOME }}

jobs:
  test:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - uses: actions/checkout@v2
      
      - name: Set up a python virtual environment
        run: | 
          sudo apt-get install python3-setuptools
          pip3 install virl2_client
          pip3 install pyats[full]
          pip install paramiko
          pip3 install nested-lookup
          pip3 install ansible
          ansible-galaxy collection install cisco.ios

      - name: Check env
        run: |
          env
          ansible --version
          pyats version check
