name: test-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VIRL2_URL: ${{ secrets.VIRL2_URL }}
  VIRL2_USER: ${{ secrets.VIRL2_USER }}
  VIRL2_PASS: ${{ secrets.VIRL2_PASS }}

jobs:
  test:
    runs-on: cml2-controller
    environment: CML2-Controller

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get CML2 API access token and set it to environment variable
        run: > 
          export ACCESS_TOKEN=$(curl -k -X POST "https://10.0.191.13/api/v0/authenticate" 
          -H  "accept: application/json" -H  "Content-Type: application/json" 
          -d "{\"username\":\"admin\",\"password\":\"P@ssw0rd\"}" | tr -d \")

      # Runs a set of commands using the runners shell
      - name: Check token
        run: |
          echo $ACCESS_TOKEN
          echo $VIRL2_URL
