name: test-ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  VIRL2_URL: ${{ secrets.VIRL2_URL }}
  VIRL2_USER: ${{ secrets.VIRL2_USER }}
  VIRL2_PASS: ${{ secrets.VIRL2_PASS }}

jobs:
  test:
    runs-on: cml2-controller
    environment: CML2-Controller

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Check env
        run: env

      # Runs a set of commands using the runners shell
      - name: Print env secrets
        run: |
          echo $VIRL2_URL
          echo $VIRL2_USER
